import './globals.css';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import { store } from "../store/store";
import { Provider } from "react-redux";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
         <AuthProvider>{children}</AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
